# file generated by setuptools-scm
# don't change, don't track in version control

from .exceptions import ValidationError
from .config import configure

__version__ = '0.2.2'
__version_tuple__ = (0, 2, 2)
version = __version__
version_tuple = __version_tuple__

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "ValidationError",
    "ask",
    "ask_batch",
    "configure",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
