name: Publish to PyPI

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write  # PyPIの信頼できる発行者のために追加

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create and activate virtual environment
      run: |
        uv venv
        echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv pip install -e .
        uv pip install build twine python-semantic-release

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create CHANGELOG.md if it doesn't exist
      run: |
        if [ ! -f CHANGELOG.md ]; then
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: add initial CHANGELOG.md" || true
        fi

    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        # semantic-releaseを一度だけ実行（version と publish を統合）
        semantic-release --verbosity DEBUG
